### ISSUE TITLE
problem in the code bro

### ISSUE THREAD

**Issue by SaiKrishna38** [zakaria-narjis/Diet-Recommendation-System#1]
Backend code is not working with frontend .I tried so many times. Bro check the code properly.

**Comment by zakaria-narjis** [comment]
Hello,
It was an issue with the api endpoit port. It should have been http://backend:8080/predict/ rather than http://backend/predict/ in [Diet-Recommendation-System](https://github.com/zakaria-narjis/Diet-Recommendation-System)/[Streamlit_Frontend](https://github.com/zakaria-narjis/Diet-Recommendation-System/tree/main/Streamlit_Frontend)/Generate_Recommendations.py. Nevertheless, if you are running front end and backend directly on your machine, you should change the endpoit to http://your_ip:8080/predict/.
Thanks for mentioning this issue.

**Comment by SaiKrishna38** [comment]
I can't understand can you explain and can you give commands to run the code

**Comment by zakaria-narjis** [comment]
I corrected the issue so you have to retry the setup part https://github.com/zakaria-narjis/Diet-Recommendation-System#whale-again
